# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up MySQL 5.7
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 5.7
        mysql database: test
        mysql root password: password

    - uses: actions/checkout@v2
      name: test code
    - run: npm install
    - run: npm run-script test
      env:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        DB_NAME: test
        MYSQL_USER: root
        MYSQL_PASSWORD: password
